@ProductInventory.Api_HostAddress = http://localhost:5048

GET {{ProductInventory.Api_HostAddress}}/health/live
Accept: application/json

###

GET {{ProductInventory.Api_HostAddress}}/api/products?page=1&pageSize=20
Accept: application/json

###

GET {{ProductInventory.Api_HostAddress}}/api/products/summary
Accept: application/json
